version: '3.9'

services:
  web:
    build: .
    command: gunicorn crm_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # depends_on:   # <-- bu qatorni olib tashlang, chunki db servisi yo‘q

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
